### ISSUE TITLE
 no matching function for call to 'LITTLEFSImpl::open(const char*&, const char [2])'

### ISSUE THREAD

**Issue by hongthiet1994** [khoih-prog/ESPAsync_WiFiManager#98] opened 2022-07-29 04:14 UTC
![image](https://user-images.githubusercontent.com/29925688/181681626-02f4fc1b-5a55-4d7c-a395-4585f2cd158d.png)

I had this error

**Comment by khoih-prog** [comment] 2022-07-30 18:46
Hi @hongthiet1994 

It's better to use the new ESP32 core v1.0.6+, such as ESP32 core **v2.0.4**, either in Arduino IDE or PIO.

Check

1. [**Unable to figure out why 'LittleFS' was not declared in this scope** #96](https://github.com/khoih-prog/ESPAsync_WiFiManager/discussions/96)
2.  [**Platformio Build Error - no matching function for call to 'LITTLEFSImpl::open** #93](https://github.com/khoih-prog/ESPAsync_WiFiManager/issues/93) and many threads in PIO relating to deprecated lorol's LITTLEFS
3. [**SPIFFS failed!. Please use LittleFS or EEPROM. Stay forever** #95](https://github.com/khoih-prog/ESPAsync_WiFiManager/issues/95)

If still having problem, use Arduino IDE. Moving on to PIO only your code is compiled OK / working. Post the issue on [PIO Forum](https://community.platformio.org/) to ask for help then.

I'm closing the issue now as this is not a bug of the library.

Good Luck,

---

PS:

Next time, you have to follow the instructions in [**Issue: Bug report**](https://github.com/khoih-prog/ESPAsync_WiFiManager/issues/new?assignees=&labels=&template=bug_report.md&title=) and don't post the picture, but the whole error messages, wrapped in `code` style.

For example

```
.pio/libdeps/esp32dev/LittleFS_esp32/src/LITTLEFS.cpp:44:28: error: no matching function for call to 'LITTLEFSImpl::open(const char*&, const char [2])'
...
```

**Closed by khoih-prog** 2022-07-30 18:46 UTC
